# NAME: Justin Pank
# EMAIL: jtpank@g.ucla.edu
# ID: 204417822 

build: 3b.py
	rm -rf lab3b ;ln -s lab3b.py 3b.py lab3b ;chmod +x 3b.py; echo "created Symlink succesfully\n"

dist: 
	tar -zcvf lab3b-204417822.tar.gz lab3b.py README Makefile

clean:
	rm -rf *.tar.gz lab3b *~

