# NAME: Justin Pank
# EMAIL: jtpank@g.ucla.edu
# ID: 204417822 
dist:
	tar -czf lab4a-204417822.tar.gz my_beaglebone.png connected.png copy.png build_run.png git.png README Makefile
clean:
	rm my_beaglebone.png connected.png copy.png build_run.png git.png README Makefile

